sudo: false
language: go
go:
- 1.6
- 1.7
- 1.7.1
- tip
script: make
matrix:
  allow_failures:
  - go: tip
notifications:
  slack:
    secure: WQ1v6XL0he7nxhYUoXMCmQ7mxeSNQsz54z+yVw0LhDDIoWuhPmucV9es/yjTrebe7ZfrM8bmxYLxVVKgphQiXmZx/T76z3zZLNv/BfisLQeT2h1AVxHZ78UK8D3nTrdHM0rvosDv2dq6hC0WxtAZWEP/mGf3Nk+4dBLr4scddYyatApThCD50g1uX/kFs6a44OQ+NrxHFgWgN3NUkUDMMylhtd1mXmy1UDPlElc5h/tAspnrfOh4LwZeKl7lz1CdNDMJURwx8ZdVY22EvwPZISxCa4X6oYpoRoXt2zJ/JJE+H6ICwbo1nXbR6dMHnaZ0EWqgkIQUpGQixAdrsyBt8ddV+lrl6HzyMJcno7aae68oHyipJ5pv8/qQsbLlMlOPWCMeIXZpnzaE/dDLLy/3MZHUa4AWfv0xIHKJN7bhKz8dxfc8bqy/KHvIbbAAWUUBub2F9SRb4LK265skIZmIOLCgqAtKp3THwmhucJhLX4+Gt5ioCx6Cw/HDLD8g4uqR9eUPpRyLVn/ntEzERNPhqWzaHHesIVb3mNfOW3AtLkKfxtdICX4be5AGuhbvKljiFDyf7X582UrbfmfnV1Tjb8elDl8i9/bXFrrv+XtdFuvp2aioIZp81KX9BMVBXiDfugTVLjvwYuGxbxP75cym7jg1uYsMwvKduouQ+N9BRxE=
